version: "3"
services:
  api:
    image: golang:1.10.3
    restart: always
    working_dir: /go/src/vanekt/dental-api
    entrypoint: /usr/bin/run.sh
    volumes:
      - ./api/run.sh:/usr/bin/run.sh:ro
      - ${GOPATH}/src:/go/src:rw
      - ${GOPATH}/src/vanekt/dental-api:/go/src/vanekt/dental-api:ro
    ports:
     - ${API_PORT}:4000
    environment:
      PORT: 4000
      SITEHOST: ${SITEHOST}
      SQL_DB_DSN: "root:root@tcp(db:3306)/dental"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    depends_on:
      - db
  db:
    image: percona:5.7
    volumes:
#    - ./db/:/docker-entrypoint-initdb.d/
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db
volumes:
  mysql-data:
    driver: local
